version: 0.2

env:
  secrets-manager:
    FIREBASE_SERVICE_ACCOUNT: "arn:aws:secretsmanager:us-east-1:346518713419:secret:fire-name::"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "== Install phase =="
      - npm install -g firebase-tools
      - apt-get update && apt-get install -y jq curl

  pre_build:
    commands:
      - echo "== Pre-build phase =="
      - echo "$FIREBASE_SERVICE_ACCOUNT" > /root/firebase-key.json
      - export GOOGLE_APPLICATION_CREDENTIALS=/root/firebase-key.json
      - export PROJECT_ID=physioprescription-98af8
      - curl -sSL https://sdk.cloud.google.com | bash
      - export PATH=$PATH:/root/google-cloud-sdk/bin
      - gcloud auth activate-service-account --key-file=/root/firebase-key.json
      - gcloud config set project $PROJECT_ID
      - cd physio-prescriptions-v2
      - npm install

  build:
    commands:
      - echo "== Build phase =="
      - npm run build

  post_build:
    commands:
      - echo "== Deploying to Firebase Hosting =="
      - cd ..
      - npx firebase deploy --only hosting --project $PROJECT_ID --non-interactive
      - echo "Build finished. Firebase key used from $GOOGLE_APPLICATION_CREDENTIALS"