version: 0.2

env:
  variables:
    GOOGLE_APPLICATION_CREDENTIALS: "/root/firebase-key.json"
    PROJECT_ID: "physioprescription-98af8"
  secrets-manager:
    FIREBASE_SERVICE_ACCOUNT: "arn:aws:secretsmanager:us-east-2:346518713419:secret:firebase-service-account-LmTAnc"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "== Install phase =="
      - npm install -g firebase-tools
      - echo "$FIREBASE_SERVICE_ACCOUNT" > /root/firebase-key.json
      - echo "Service account file created at $GOOGLE_APPLICATION_CREDENTIALS"

  pre_build:
    commands:
      - echo "== Pre-build phase =="
      - echo "Service account file first 5 lines (for debugging):"
      - head -n 5 /root/firebase-key.json
      - cd physio-prescriptions-v2
      - npm install

  build:
    commands:
      - echo "== Build phase =="
      - npm run build

  post_build:
    commands:
      - echo "== Deploying to Firebase Hosting =="
      - echo "GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS"
      - echo "PROJECT_ID: $PROJECT_ID"
      - cd ..
      - firebase deploy --only hosting --project $PROJECT_ID --non-interactive