
version: 0.2
env:
  secrets-manager:
    FIREBASE_TOKEN: "arn:aws:secretsmanager:us-east-1:346518713419:secret:firebaseServiceAccount-key-xvHPza"
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y nodejs
      - npm install -g firebase-tools
      # Save your secret as a JSON file that Firebase CLI expects:
      - echo $FIREBASE_SERVICE_ACCOUNT > /root/serviceAccount.json
      - export GOOGLE_APPLICATION_CREDENTIALS=/root/serviceAccount.json
  pre_build:
    commands:
      - cd physio-prescriptions-v2
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - cd ..
      - firebase deploy --only hosting