version: 0.2

env:
  secrets-manager:
    FIREBASE_SERVICE_ACCOUNT: "arn:aws:secretsmanager:us-east-1:346518713419:secret:fire-name::"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "== Install phase =="
      - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y nodejs
      - echo "$FIREBASE_SERVICE_ACCOUNT" > /root/firebase-key.json
      - export GOOGLE_APPLICATION_CREDENTIALS=/root/firebase-key.json
      - echo "GOOGLE_APPLICATION_CREDENTIALS is set to $GOOGLE_APPLICATION_CREDENTIALS"
      - cat /root/firebase-key.json | head -n 5   # just first 5 lines for debugging

  pre_build:
    commands:
      - echo "== Pre-build phase =="
      - cd physio-prescriptions-v2
      - npm install

  build:
    commands:
      - echo "== Build phase =="
      - npm run build

  post_build:
    commands:
      - echo "== Post-build phase =="
      - echo "Build finished. Firebase key available at $GOOGLE_APPLICATION_CREDENTIALS"