version: 0.2

env:
  secrets-manager:
    FIREBASE_SERVICE_ACCOUNT: "arn:aws:secretsmanager:us-east-2:346518713419:secret:firebase-service-account-LmTAnc"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "== Install phase =="
      - npm install -g firebase-tools
      - echo "$FIREBASE_SERVICE_ACCOUNT" > /root/firebase-key.json
      - export GOOGLE_APPLICATION_CREDENTIALS=/root/firebase-key.json
      - export PROJECT_ID=physioprescription-98af8
      - echo "GOOGLE_APPLICATION_CREDENTIALS is set to $GOOGLE_APPLICATION_CREDENTIALS"

  pre_build:
    commands:
      - echo "== Pre-build phase =="
      - echo "Service account file first 5 lines (for debugging):"
      - head -n 5 /root/firebase-key.json
      - cd physio-prescriptions-v2
      - npm install

  build:
    commands:
      - echo "== Build phase =="
      - npm run build

  post_build:
    commands:
      - echo "== Deploying to Firebase Hosting =="
      - cd ..
      - firebase deploy --only hosting --project $PROJECT_ID --non-interactive