version: 0.2

env:
  secrets-manager:
    FIREBASE_SERVICE_ACCOUNT: "arn:aws:secretsmanager:us-east-1:346518713419:secret:fire-name::"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "STEP 1: Install phase"
      - echo "Secret length: ${#FIREBASE_SERVICE_ACCOUNT}"
      - echo "$FIREBASE_SERVICE_ACCOUNT" > firebase-key.json
      - echo "Saved secret to firebase-key.json"