version: 0.2

env:
  secrets-manager:
    FIREBASE_SERVICE_ACCOUNT: "arn:aws:secretsmanager:us-east-2:346518713419:secret:firebase-service-account-LmTAnc"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "== Install phase =="
      - npm install -g firebase-tools
      - echo "$FIREBASE_SERVICE_ACCOUNT" > /root/firebase-key.json
      - export GOOGLE_APPLICATION_CREDENTIALS=/root/firebase-key.json
      - export PROJECT_ID=physioprescription-98af8
      - echo "GOOGLE_APPLICATION_CREDENTIALS is set"

  pre_build:
    commands:
      - echo "== Pre-build phase =="
      - cat /root/firebase-key.json | head -n 20
      - gcloud auth activate-service-account --key-file=/root/firebase-key.json
      - gcloud config set project $PROJECT_ID
      - cd physio-prescriptions-v2
      - npm install

  build:
    commands:
      - echo "== Build phase =="
      - npm run build

  post_build:
    commands:
      - echo "== Deploying to Firebase Hosting =="
      - cd ..
      - npx firebase deploy --only hosting --project $PROJECT_ID --non-interactive