version: 0.2

env:
  secrets-manager:
    FIREBASE_SERVICE_ACCOUNT: "arn:aws:secretsmanager:us-east-1:346518713419:secret:fire-name-eVkQBl::"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "STEP 1: Install phase"
      - echo "Secret length: ${#FIREBASE_SERVICE_ACCOUNT}"
  build:
    commands:
      - echo "STEP 2: Build phase"