version: 0.2

env:
  variables:
    GOOGLE_APPLICATION_CREDENTIALS: "/root/firebase-key.json"
    PROJECT_ID: "physioprescription-98af8"
  secrets-manager:
    FIREBASE_SERVICE_ACCOUNT: "arn:aws:secretsmanager:us-east-2:346518713419:secret:firebase-service-account-LmTAnc"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "== Install phase =="
      # Install Firebase CLI
      - npm install -g firebase-tools
      # Fetch service account JSON
      - echo "$FIREBASE_SERVICE_ACCOUNT" > $GOOGLE_APPLICATION_CREDENTIALS
      - echo "Service account JSON saved"

      # Install Google Cloud SDK
      - echo "Installing Google Cloud SDK..."
      - apt-get update && apt-get install -y apt-transport-https ca-certificates gnupg curl
      - echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" \
          | tee /etc/apt/sources.list.d/google-cloud-sdk.list
      - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg \
          | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
      - apt-get update && apt-get install -y google-cloud-cli
      - echo "Google Cloud SDK installed; version:$(gcloud --version)"

      # Authenticate gcloud with service account
      - gcloud auth activate-service-account --key-file="$GOOGLE_APPLICATION_CREDENTIALS"
      - gcloud config set project $PROJECT_ID

  pre_build:
    commands:
      - echo "== Pre-build phase =="
      - head -n 5 $GOOGLE_APPLICATION_CREDENTIALS
      - cd physio-prescriptions-v2
      - npm install

  build:
    commands:
      - echo "== Build phase =="
      - npm run build

  post_build:
    commands:
      - echo "== Deploying to Firebase Hosting =="
      - cd ..
      - firebase deploy --only hosting --project $PROJECT_ID --non-interactive

artifacts:
  files:
    - '**/*'