version: 0.2

env:
  secrets-manager:
    FIREBASE_SERVICE_ACCOUNT: "arn:aws:secretsmanager:us-east-1:346518713419:secret:fire-name::"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "== Install phase =="
      - npm install -g firebase-tools
      # Save service account JSON to a file
      - echo "$FIREBASE_SERVICE_ACCOUNT" > /root/firebase-key.json
      - export GOOGLE_APPLICATION_CREDENTIALS=/root/firebase-key.json
      - export PROJECT_ID=physioprescription-98af8
      - echo "GOOGLE_APPLICATION_CREDENTIALS set to $GOOGLE_APPLICATION_CREDENTIALS"

  pre_build:
    commands:
      - echo "== Pre-build phase =="
      - cd physio-prescriptions-v2
      - npm install

  build:
    commands:
      - echo "== Build phase =="
      - npm run build

  post_build:
    commands:
      - echo "== Deploying to Firebase Hosting =="
      - npx firebase deploy --only hosting --project $PROJECT_ID --non-interactive
      - echo "Build finished."