version: 0.2

env:
  secrets-manager:
    FIREBASE_SERVICE_ACCOUNT: "arn:aws:secretsmanager:us-east-1:346518713419:secret:fire-name-eVkQBl::"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "STEP 1: Installing"
      - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y nodejs
      - npm install -g firebase-tools
      - "echo \"$FIREBASE_SERVICE_ACCOUNT\" > /root/serviceAccount.json"
      - export GOOGLE_APPLICATION_CREDENTIALS=/root/serviceAccount.json
      - echo "GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS"
      - cat /root/serviceAccount.json

  build:
    commands:
      - echo "STEP 2: Building"
      - npm run build